# Generated by Django 3.2.3 on 2021-06-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_teammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='position_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='position_ru',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
