# Generated by Django 3.2.3 on 2021-06-17 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_productcommentmodel_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price')),
                ('firstname', models.CharField(max_length=20, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=20, verbose_name='lastname')),
                ('companyname', models.CharField(max_length=50, verbose_name='companyname')),
                ('zipcode', models.CharField(max_length=10, verbose_name='zipcode')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('product', models.ManyToManyField(related_name='orders', to='products.ProductModel', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
