# Generated by Django 3.2.3 on 2021-06-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentmodel',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.productmodel', verbose_name='products'),
        ),
    ]
